export const SHOW_PRODUCTS = "SHOW_PRODUCTS";
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const INVALIDATE_PRODUCTS = "INVALIDATE_PRODUCTS";


