export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const INVALIDATE_PRODUCTS = "INVALIDATE_PRODUCTS";


